services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  test:
    build:
      context: .
      target: builder
    command: cargo test --all-features -- --nocapture
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    volumes:
      - .:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
    profiles: ["test"]

volumes:
  cargo-cache: {}