services:
  app:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:developerfred/titanium}:${TAG:-latest}
    build: 
      context: .
      args:
        RUST_LOG: ${RUST_LOG:-info}
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  test:
    build:
      context: .
      target: builder
    command: cargo test --all-features -- --nocapture
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    volumes:
      - .:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
    profiles: ["test"]

volumes:
  cargo-cache: {}